from flask import Flask
from .ViewIndex import app
from .ViewIndex import ViewIndex
from .ViewArchive import ViewArchive
from .ViewUpdateImage import ViewUpdateImage
from .HandleUserRequest import HandleUserRequest
from .Factory import Factory
from .Task import Task
from .Pagination import Pagination
from .DataBase import DataBase
from .ModelDB  import ModelDB 
from .CatApi import CatApi
from .QuoteZenApi  import QuoteZenApi